### PR TITLE
Added an option for column separator

### PR DESCRIPTION
**Pull request by ABohynDOE**
This option should fix the issue if Saif tries again with the ","-separated file
@saif-analyze  could try ?

### CODE REVIEW

**Comment by dmbarreiro** [comment]
I see the following message in the merge section of this screen
```
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/DOE-police/DOEDA/pull/9/conflicts) or the to resolve conflicts.
Conflicting files
utils/data_processing/csv2json.py
```
do you see it too?
It is a bit strange cause no conflicts show on the files changed screen

**Comment by ABohynDOE** [comment]
I remove the conflicting lines, all should be fine by now

**Comment by ABohynDOE** [comment]
@dmbarreiro do you still see the conflicts ? If not, you can approve and we'll merge it

**Comment by dmbarreiro** [comment]
> @dmbarreiro do you still see the conflicts ? If not, you can approve and we'll merge it

No, I don't. We can merge this

**Review by dmbarreiro — APPROVED** [review]

**Pull request merged**
